---
title: "simulation & inference of transients"
author: "Carl Boettiger"
date: "5/30/2019"
output: github_document
---
  
```{r message = FALSE}
library(tidyverse)
library(furrr)
plan("multisession")
set.seed(12345)
```
  
```{r}
du <- function(u,v, p) u * (1 - u) - p$a12 * u ^ p$n * v
dv <- function(u, v, p) p$gamma * (v*(1-v) - p$a21 * u ^ p$n * v)
```


```{r}
stochastic_sim <- function(du, dv, p, const){
  
  # inits
  u <- v <- numeric(const$Tmax)
  u[1] <- const$u0
  v[1] <- const$v0
  
  # random draws
  dB_u <- rnorm(const$Tmax, 0, p$sigma_u)
  dB_v <- rnorm(const$Tmax, 0, p$sigma_v)

  dt <- const$dt

  # simulate
  for(t in 1:(const$Tmax-1)){
    u[t+1] <- max( 
                  u[t] + du(u[t], v[t], p) * dt  + u[t] * dB_u[t],
                  0)
    v[t+1] <- max( 
                  v[t] + dv(u[t], v[t], p) * dt + v[t] * dB_v[t],
                  0)
  }
  data.frame(t = 1:const$Tmax, u, v)
}
```



```{r}
det_sim <- function(du, dv, p, const){
  
  # inits
  u <- v <- numeric(const$Tmax)
  u[1] <- const$u0
  v[1] <- const$v0
  
  dt <- const$dt

  
  # simulate
  for(t in 1:(const$Tmax-1)){
    u[t+1] <- du(u[t], v[t], p) * dt  + u[t]
    v[t+1] <- dv(u[t], v[t], p) * dt + v[t]
  }
  data.frame(t = 1:const$Tmax, u, v)
}

```



```{r}
p <- list(a12 = 0.9, a21 = 1.1, gamma = 10, n = 1.55, sigma_u = 0.02, sigma_v = 0.02)  # n = 1.8
const <- list(u0 = 1, v0 = 1, Tmax = 800, dt = 0.01)

det <- det_sim(du,dv,p, const) 


det %>% gather(species, population, -t) %>% 
  ggplot(aes(t, population, col=species)) + geom_line()

#det %>% ggplot(aes(u, v)) + geom_path()
```


```{r}
system.time({
  df <- future_map_dfr(1:100, function(reps) stochastic_sim(du, dv, p, const), .id = "reps")
})


```


```{r}
det <- det_sim(du, dv, p, const) %>% mutate(reps=1)
mean <- df %>% group_by(t) %>% summarise(u = mean(u)) %>% mutate(reps = 1)
```

```{r}
df %>% ggplot(aes(t, u, group=reps)) + 
  geom_line(alpha=0.1) +
  geom_line(data = det, color = "blue") + 
  geom_line(data = mean, color = "red")
```


--------





```{r}
dR <- function(R, C, P, p) R * (1 - R / p$K ) - p$xc * p$yc * C * R / (R + p$R0)

dC <- function(R, C, P, p) p$xc * C * ( p$yc * R / (R + p$R0) - 1) - p$xp * p$yp * P * C / (C + p$C0)
dP <- function(R, C, P, p) p$xp * P * ( p$yp * C / (C + p$C0) - 1) 


```



````{r}
stochastic_sim <- function(dR, dC, dP, p, const){
  
  # inits
  R <- C <- P <- numeric(const$Tmax)
  R[1] <- const$R0
  C[1] <- const$C0
  P[1] <- const$P0
  # random draws
  dB_R <- rnorm(const$Tmax, 0, p$sigma_r)
  dB_C <- rnorm(const$Tmax, 0, p$sigma_c)
  dB_P <- rnorm(const$Tmax, 0, p$sigma_p)

  dt <- const$dt

  # simulate
  for(t in 1:(const$Tmax-1)){
    R[t+1] <- max( 
                  R[t] + dR(R[t], C[t], P[t], p) * dt  + R[t] * dB_R[t],
                  0)
    C[t+1] <- max( 
                  C[t] + dC(R[t], C[t], P[t], p) * dt + C[t] * dB_C[t],
                  0)
    P[t+1] <- max(
                  P[t] + dP(R[t], C[t], P[t], p) * dt + P[t] * dB_P[t],
                  0)
  }
  data.frame(t = 1:const$Tmax, R, C, P)
}
```

```{r}
dt=0.01
p <- list(xc = 0.4, yc = 2.009, xp = 0.08, yp = 2.876, R0 = 0.16129, C0 = 0.5, 
K = 1, sigma_r = 0.0, sigma_c = 0.0, sigma_p = 0.0)
const <- list(R0 = .5, C0 = .5, P0=1, Tmax = 200/dt, dt = dt)

```

```{r}
system.time({
  df <- future_map_dfr(1:10, function(reps) stochastic_sim(dR, dC, dP, p, const), .id = "reps")
})
```


```{r}
mean <- df %>% group_by(t) %>% summarise(R = mean(R), C = mean(C), P = mean(P)) %>% mutate(reps = 1)
```


```{r}
mean %>% ggplot(aes(R, C, col=t)) + 
  geom_path() 
```

```{r}
mean %>% ggplot(aes(C, P, col=t)) + 
  geom_path() 
```

```{r}
mean %>% gather(species, pop, -t) %>%
  ggplot(aes(t, pop, col=species)) + 
  geom_line()
```







generic form

```{r}


stochsim <- function(f, pars, sigma, inits, Tmax, dt = 0.01){
  
  ## Initial conditions
  X <- array(dim = c(Tmax, length(f)))
  X[1,] <- inits
  
  ## Noise terms
  dB <- lapply(sigma, function(s) rnorm(const$Tmax, 0, s))
  
  ## simulate
  for(t in 1:(const$Tmax-1)){
    for(i in length(f)){
          X[t+1,i] <- max( 
                  X[t,i] + f[[i]](X[t,], p) * dt  + X[t,i] * dB[[i]][t],
                  0)
    }
  }
  X
}


detsim <- function(f, pars, sigma, inits, Tmax, dt = 0.01){
  X <- array(dim = c(Tmax, length(f)))
  X[1,] <- inits
  
  ## Noise terms
  dB <- lapply(sigma, function(s) rnorm(const$Tmax, 0, s))
  for(t in 1:(const$Tmax-1)){
    for(i in length(f)){
          X[t+1,i] <-  X[t,i] + f[[i]](X[t,], p) * dt  
    }
  }
  X
}




sim <- function(f, pars, sigma = numeric(length(f)), inits, Tmax, dt = 0.01){

  stopifnot(equal(length(f), length(inits)))
  stopifnot(equal(length(f), length(sigma)))
  
  if(!any(is.na(sigma)) & all(sigma > 0))
    stochsim(f, pars, sigma, inits, Tmax, dt)
  else
    detsim(f, pars, sigma, inits, Tmax, dt)
}
```



```{r}
dR <- function(X, p) X[1] * (1 - (X[1] / p$K)) - p$xc * p$yc * X[2]* X[1] / (X[1] + p$R0)

dC <- function(X, p) p$xc * x[2] * ((p$yc * X[1] / (X[1] + p$R0)) - 1) - p$xp * p$yp * X[3] * X[2] / (X[2] + p$C0)
dP <- function(X, p) p$xp * X[3] * ((p$yp * X[2] / (X[2] + p$C0)) - 1) 

```


```{r}
sim(list(dR, dC, dP), p, c(0.2,0.2,0.2), c(1,1,1), 1000)
```
